server:
  port: 2030

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication-db
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: true




