server:
  port: 2030
spring:
  datasource:
    url: jdbc:h2:mem:authentication-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    generate-ddl: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  cache:
    cache-names: number
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  main:
    allow-circular-references: true
