server:
  port: 2030

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication-db
    username: postgres
    password: 12345
    tomcat:
      test-while-idle: true


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: true
  cache:
    cache-names: number
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

  main:
    allow-circular-references: true
